version: '3'
networks:
  bluesky-services_bluesky:
    external: true
services:
  nbs-viewer:
    image: ghcr.io/xraygui/nbs-pods/nbs-viewer:latest
    volumes:
      - /run/user/${HOST_UID}:/run/user/${HOST_UID}
    devices:
      - /dev/dri:/dev/dri
      - /dev/video0:/dev/video0
    environment:
      - WAYLAND_DISPLAY=${WAYLAND_DISPLAY}
      - QT_QPA_PLATFORM=wayland
      - IPYTHONDIR=/usr/local/share/ipython
      - XDG_RUNTIME_DIR=/run/user/${HOST_UID}
    command: nbs-viewer -f "/usr/local/share/ipython/profile_default/startup/viewer_config.toml"
    networks:
      - bluesky-services_bluesky
