services:
  mongo:
    image: docker.io/mongo:latest
    networks:
      - bluesky

  tiled_server:
    image: ghcr.io/bluesky/databroker:v2.0.0b65
    command: tiled serve config /etc/tiled/config --host 0.0.0.0
    volumes:
      - ${NBS_PODS_DIR}/config/tiled/config:/etc/tiled/config
      - /tmp/proposals:/nsls2/data/sst/proposals
    ports:
      - "8000:8000"
    networks:
      - bluesky
