version: '3'

services:
  bluesky:
    build:
      context: .
      dockerfile: images/bluesky/Containerfile
    image: localhost/nbs-bluesky:latest

  queueserver:
    build:
      context: .
      dockerfile: images/queueserver/Containerfile
      args:
        BASE_IMAGE: localhost/nbs-bluesky:latest
    image: localhost/nbs-queueserver:latest
    depends_on:
      - bluesky

  gui:
    build:
      context: .
      dockerfile: images/gui/Containerfile
      args:
        BASE_IMAGE: localhost/nbs-bluesky:latest
    image: localhost/nbs-gui:latest
    depends_on:
      - bluesky

  viewer:
    build:
      context: .
      dockerfile: images/viewer/Containerfile
      args:
        BASE_IMAGE: localhost/nbs-bluesky:latest
    image: localhost/nbs-viewer:latest
    depends_on:
      - bluesky

  sim:
    build:
      context: .
      dockerfile: images/sim/Containerfile
      args:
        BASE_IMAGE: localhost/nbs-bluesky:latest
    image: localhost/nbs-sim:latest
    depends_on:
      - bluesky
