version: '3'
networks:
  bluesky-services_bluesky:
    external: true
services:
  qs-gui:
    image: nbs_gui:latest
    volumes:
      - /run/user/${HOST_UID}/${WAYLAND_DISPLAY}:/tmp/${WAYLAND_DISPLAY}
      - ${BEAMLINE_PODS_DIR}/config/bluesky:/etc/bluesky
      - ${NBS_PODS_DIR}/config/ipython:/usr/local/share/ipython
      - ${NBS_PODS_DIR}/config/tiled:/etc/tiled

    environment:
      - WAYLAND_DISPLAY=${WAYLAND_DISPLAY}
      - QT_QPA_PLATFORM=wayland
      - IPYTHONDIR=/usr/local/share/ipython
      - XDG_RUNTIME_DIR=/tmp
      - EPICS_CA_AUTO_ADDR_LIST=YES
      - QSERVER_ZMQ_INFO_ADDRESS=tcp://acq_qs:60625
      - QSERVER_ZMQ_CONTROL_ADDRESS=tcp://acq_qs:60615
    command: nbs-gui --profile default
    networks:
      - bluesky-services_bluesky
