[configuration]
baseline = ['motors', 'shutters', 'mirrors', 'manipulators', 'apertures']
has_slits = true
has_motorized_samples = true
has_motorized_eref = true
has_polarization = true

[detector_sets.default]
primary = "sc"
normalization = "i0"
reference = "ref"

[devices]
i0 = { threshold = 0.1, description = "Gold Mesh"}
i1 = { threshold = 0.1, description = "Back Diode"}
sc = { threshold = 0.1 }
ref = { threshold = 0.1 }

[settings]
modules = ['ucal.startup']
tes_processing = "/usr/local/share/ipython/profile_default/startup"

[settings.plans]
xas = ['regions.toml']

[settings.redis.md]
host = "redis"
prefix = "nexafs-"

[settings.redis.info]
host = "redisInfo"
prefix = "nexafs-"
port = 60737
db = 4