[configuration]
baseline = ['motors', 'shutters', 'mirrors', 'manipulators', 'apertures']

[detector_sets.default]
primary = "sc"
normalization = "i0"
reference = "ref"

[devices]
i0 = { threshold = 0.1, description = "Gold Mesh"}
i1 = { threshold = 0.1, description = "Back Diode"}
sc = { threshold = 0.1 }
ref = { threshold = 0.1 }

[startup]
modules = ['ucal.startup']
regions = ['regions.toml']