FROM bluesky

RUN pip3 install git+https://github.com/xraygui/nbs-core
RUN pip3 install git+https://github.com/xraygui/nbs-bl
RUN pip3 install git+https://github.com/xraygui/nbs-sim
RUN pip3 install git+https://github.com/xraygui/livetable

# Create configuration directories
RUN mkdir -p /etc/tiled/profiles
RUN mkdir -p /etc/bluesky

# Copy default configurations
COPY config/tiled/profiles/ /etc/tiled/profiles/
COPY config/bluesky/ /etc/bluesky/

LABEL version="0.0.1" 
