version: '3'

networks:
  bluesky-services_bluesky:
    external: true

services:
  main:
    image: ${NBS_IMAGE_REG:-ghcr.io/xraygui/nbs-pods/}sim:latest
    command: pixi run sim
    dns:
      - 10.89.0.1
    networks:
      - bluesky-services_bluesky
