ARG BASE_IMAGE=nbs
FROM ${BASE_IMAGE}

RUN dnf -y install qt5-qtbase-devel qt5-qtwayland

RUN pip3 install PyQt5

RUN pip3 install git+https://github.com/xraygui/nbs-viewer@v0.3.0

CMD ["nbs-viewer"]

LABEL version="0.0.1" 