version: '3'

services:
  queueserver:
    volumes:
      - ${BEAMLINE_PODS_DIR}/config/ipython:/usr/local/share/ipython
      - ${NBS_PODS_DIR}/config/tiled/profiles:/etc/tiled/profiles
      - ${NBS_PODS_DIR}/config/bluesky:/etc/bluesky
      - ${NBS_COLLECTION_PACKAGES}:/usr/local/src/collection_packages
    command: pixi run qs-dev
