version: '3'

networks:
  bluesky-services_bluesky:
    external: true

services:
  queueserver:
    image: ${NBS_IMAGE_REG:-ghcr.io/xraygui/nbs-pods/}queueserver:latest
    environment:
      - IPYTHONDIR=/usr/local/share/ipython
      - EPICS_CA_AUTO_ADDR_LIST=yes
      - NBS_SIM_MODE=1
      - QS_REDIS_ADDR=redis
    command: pixi run qs
    volumes:
      - /tmp/proposals:/nsls2/data/sst/proposals
    dns:
      - 10.89.0.1
    networks:
      - bluesky-services_bluesky
