FROM fedora

ENV CONDA_DIR=/opt/conda
ENV PATH=/opt/conda/bin:$PATH

RUN dnf install -y wget git g++ gcc

RUN wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh && \
    /bin/bash ~/miniconda.sh -b -p /opt/conda

LABEL version="0.0.1" 