version: '3'
networks:
  bluesky-services_bluesky:
    external: true
services:
  main:
    image: ${NBS_IMAGE_REG:-ghcr.io/xraygui/nbs-pods/}gui:latest
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    environment:
      - DISPLAY=${DISPLAY}
      - QT_QPA_PLATFORM=xcb
      - IPYTHONDIR=/usr/local/share/ipython
      - EPICS_CA_AUTO_ADDR_LIST=YES
      - QSERVER_ZMQ_INFO_ADDRESS=tcp://acq_qs:60625
      - QSERVER_ZMQ_CONTROL_ADDRESS=tcp://acq_qs:60615
      - NBS_SIM_MODE=1
    command: pixi run gui
    dns:
      - 10.89.0.1
    networks:
      - bluesky-services_bluesky
    cap-add:
      - SYS_PTRACE
