name: Build and Push Container Images

on:
  push:
    branches: [ main, containerfiles ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Manual trigger

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        driver-opts: network=host

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push bluesky to local registry
      run: |
        docker build -t localhost:5000/bluesky:latest -f images/bluesky/Containerfile .
        docker push localhost:5000/bluesky:latest

    - name: Build and push nbs to local registry
      run: |
        docker build -t localhost:5000/nbs:latest -f images/nbs/Containerfile .
        docker push localhost:5000/nbs:latest

    - name: Build and push nbs-gui to local registry
      run: |
        docker build -t localhost:5000/nbs-gui:latest -f images/gui/Containerfile .
        docker push localhost:5000/nbs-gui:latest

    - name: Tag and push bluesky to GHCR
      run: |
        docker tag localhost:5000/bluesky:latest ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/bluesky:latest
        docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/bluesky:latest

    - name: Tag and push nbs to GHCR
      run: |
        docker tag localhost:5000/nbs:latest ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/nbs:latest
        docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/nbs:latest

    - name: Tag and push nbs-gui to GHCR
      run: |
        docker tag localhost:5000/nbs-gui:latest ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/nbs-gui:latest
        docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/nbs-gui:latest 