name: Build and Push Container Images

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Manual trigger

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build bluesky image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./images/bluesky/Containerfile
        push: false
        tags: bluesky:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Build nbs image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./images/nbs/Containerfile
        push: false
        tags: nbs:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Build nbs-gui image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./images/gui/Containerfile
        push: false
        tags: nbs-gui:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Tag and push bluesky to GHCR
      run: |
        docker tag bluesky:latest ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/bluesky:latest
        docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/bluesky:latest

    - name: Tag and push nbs to GHCR
      run: |
        docker tag nbs:latest ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/nbs:latest
        docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/nbs:latest

    - name: Tag and push nbs-gui to GHCR
      run: |
        docker tag nbs-gui:latest ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/nbs-gui:latest
        docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/nbs-gui:latest 