name: Build and Push Container Images

on:
  push:
    branches: [ main, containerfiles ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Manual trigger

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push bluesky image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./images/bluesky/Containerfile
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/bluesky:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Build and push nbs image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./images/nbs/Containerfile
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/nbs:latest
        build-args: |
          BASE_IMAGE=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/bluesky:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Build and push nbs-gui image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./images/gui/Containerfile
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/nbs-gui:latest
        build-args: |
          BASE_IMAGE=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/nbs:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max 